CODE elcirculo.ulx
PICTURE Logo_Alpha_Aventuras_jpg res/img/logo_alpha_aventuras.jpg
PICTURE Logo_Alpha_Aventuras_Corto_jpg res/img/logo_alpha_aventuras_corto.jpg
PICTURE Prologo_png res/img/prologo.png
PICTURE Oscuridad_jpg res/img/oscuridad.jpg
PICTURE Fundido_png res/img/fundido.png
PICTURE Logo_Circulo_png res/img/logo_circulo.png
PICTURE Logo_Circulo_Solo_Letras_png res/img/logo_circulo_solo_letras.png
PICTURE Cuarto_Katie_jpg res/img/cuarto_katie.jpg
PICTURE Cuarto_Katie_TV_Encendida_jpg res/img/cuarto_katie_tv_encendida.jpg
PICTURE Pasillo_Katie_jpg res/img/pasillo_katie.jpg
PICTURE Pasillo_Katie_Charco_jpg res/img/pasillo_katie_charco.jpg
!PICTURE Cocina_Katie_Prologo_jpg res/img/cocina_katie_prologo.jpg
PICTURE Cocina_Katie_jpg res/img/cocina_katie.jpg
PICTURE Cocina_Frigo_Abierto_jpg res/img/cocina_frigo_abierto.jpg
PICTURE Salon_Katie_jpg res/img/salon_katie.jpg
PICTURE Salon_Katie_TV_Encendida_jpg res/img/salon_katie_tv_encendida.jpg
PICTURE Fin_Prologo1_jpg res/img/fin_prologo1.jpg
PICTURE Fin_Prologo2_jpg res/img/fin_prologo2.jpg
PICTURE Fin_Prologo3_jpg res/img/fin_prologo3.jpg
PICTURE Fin_Prologo4_jpg res/img/fin_prologo4.jpg
PICTURE Fin_Prologo5_jpg res/img/fin_prologo5.jpg
PICTURE Nieve_TV1_jpg res/img/nieve_tv1.jpg
PICTURE Nieve_TV2_jpg res/img/nieve_tv2.jpg
PICTURE Nieve_TV3_jpg res/img/nieve_tv3.jpg
SOUND Darkwalk_ogg res/snd/darkwalk.ogg
SOUND Gathering_Darkness_ogg res/snd/gathering_darkness.ogg
SOUND Grillos_ogg res/snd/grillos.ogg
SOUND TV_Fondo_ogg res/snd/tv_fondo.ogg
SOUND TV_Ruido_ogg res/snd/tv_ruido.ogg
SOUND TV_Apaga_ogg res/snd/tv_apaga.ogg
SOUND Telefono1_ogg res/snd/telefono1.ogg
SOUND Mujer_Gritando_ogg res/snd/mujer_gritando.ogg

